project:
  type: website

website:
  title: "Feidhelm Joyce"
  # favicon: images/favicon.png   # (optional; only if the file exists)
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Professional Summary
        href: professionalsummary.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




