project:
  type: website
  

website:
  title: "Feidhelm Joyce"
  favicon: 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professionalsummary.qmd
        text: Professional Summary 
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV 
      - href: contact.qmd
        text: Contact 
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




